
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDEnonassocUMINUSDIVIDE LPAREN MINUS NUMBER PLUS RPAREN TIMESexpression : expression PLUS expressionexpression : expression MINUS expressionexpression : expression TIMES expressionexpression : expression DIVIDE expressionexpression : MINUS expression %prec UMINUSexpression : LPAREN expression RPARENexpression : NUMBER'
    
_lr_action_items = {'MINUS':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,],[2,6,2,2,-7,2,2,2,2,-5,6,-1,-2,-3,-4,-6,]),'LPAREN':([0,2,3,5,6,7,8,],[3,3,3,3,3,3,3,]),'NUMBER':([0,2,3,5,6,7,8,],[4,4,4,4,4,4,4,]),'$end':([1,4,9,11,12,13,14,15,],[0,-7,-5,-1,-2,-3,-4,-6,]),'PLUS':([1,4,9,10,11,12,13,14,15,],[5,-7,-5,5,-1,-2,-3,-4,-6,]),'TIMES':([1,4,9,10,11,12,13,14,15,],[7,-7,-5,7,7,7,-3,-4,-6,]),'DIVIDE':([1,4,9,10,11,12,13,14,15,],[8,-7,-5,8,8,8,-3,-4,-6,]),'RPAREN':([4,9,10,11,12,13,14,15,],[-7,-5,15,-1,-2,-3,-4,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,3,5,6,7,8,],[1,9,10,11,12,13,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS expression','expression',3,'p_expression_plus','main.py',49),
  ('expression -> expression MINUS expression','expression',3,'p_expression_minus','main.py',53),
  ('expression -> expression TIMES expression','expression',3,'p_expression_times','main.py',57),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_divide','main.py',61),
  ('expression -> MINUS expression','expression',2,'p_expression_uminus','main.py',69),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','main.py',73),
  ('expression -> NUMBER','expression',1,'p_expression_number','main.py',77),
]
